/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tasks;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    private final App classUnderTest = new App();

    @Test
    public void testAppHasAGreeting() {
        /*
         * This is a dirty hack around increasing the code coverage,
         * since at this point in time Gradle 6.0 is not supporting
         * Jacoco excludes.
         */
        App.main(null);
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
