/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tasks;

public class App {
  // TODO : Fix the excludes with jacoco and gradle 6.0
  
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
